const ROLES = require('../constants/roles');
const FACILITY_STATUS = require('../constants/facilityStatus');
const BOOKING_STATUS = require('../constants/bookingStatus');

const seedUsers = [
  {
    name: 'Admin QuickCourt',
    email: 'admin@quickcourt.com',
    password: 'Password123!',
    role: ROLES.ADMIN,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98765 43210',
    bio: 'Chief Platform Administrator for QuickCourt Operations.',
    isVerified: true,
  },
  {
    name: 'Rajesh Sharma',
    email: 'owner@quickcourt.com',
    password: 'Password123!',
    role: ROLES.FACILITY_OWNER,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98220 11223',
    bio: 'Sports complex owner with premium badminton, turf, and tennis arenas.',
    isVerified: true,
  },
  {
    name: 'Vikram Mehta',
    email: 'vikram.owner@quickcourt.com',
    password: 'Password123!',
    role: ROLES.FACILITY_OWNER,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    phone: '+91 97112 33445',
    bio: 'Founder of Velocity Sports Hub and urban cricket turfs.',
    isVerified: true,
  },
  {
    name: 'Aarav Patel',
    email: 'user@quickcourt.com',
    password: 'Password123!',
    role: ROLES.USER,
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    phone: '+91 99887 76655',
    bio: 'Weekend badminton enthusiast and competitive local tournament player.',
    isVerified: true,
  },
  {
    name: 'Priya Iyer',
    email: 'priya@quickcourt.com',
    password: 'Password123!',
    role: ROLES.USER,
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98450 99887',
    bio: 'Tennis enthusiast and table tennis club member.',
    isVerified: true,
  },
];

const seedFacilities = [
  {
    key: 'apex',
    name: 'Apex Smash Arena & Badminton Club',
    location: 'Indiranagar, Metro Sports Corridor',
    address: 'Plot 42, 100 Feet Road, Indiranagar, Bengaluru, 560038',
    description: 'Premier indoor badminton arena featuring BWF standard synthetic cushion courts, LED anti-glare floodlighting, and air-conditioned players lounge.',
    aboutVenue: 'Apex Smash Arena was established to deliver world-class indoor sports facilities to athletes and casual players alike. Equipped with professional Yonex mats, high-ceiling climate control, clean shower rooms, and certified stringing services on-site.',
    sportsSupported: ['Badminton', 'Table Tennis'],
    amenities: ['Air Conditioning', 'Free High-Speed Wi-Fi', 'Changing Rooms & Showers', 'Cafeteria', 'Equipment Rental', 'Free Parking', 'Drinking Water'],
    photos: [
      'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1521537634581-0dced2fee2ef?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=1000&auto=format&fit=crop&q=80',
    ],
    venueType: 'Indoor',
    startingPrice: 450,
    rating: 4.9,
    reviewCount: 38,
    status: FACILITY_STATUS.APPROVED,
    operatingHours: { open: '06:00', close: '23:00' },
  },
  {
    key: 'velocity',
    name: 'Velocity Sports Turf & Box Cricket Arena',
    location: 'Koramangala, 5th Block',
    address: 'Near Forum Nexus, Hosur Main Road, Koramangala, Bengaluru, 560095',
    description: 'FIFA-approved artificial 50mm grass turf for 5-a-side football and high-intensity box cricket with overhead safety netting and stadium-grade floodlights.',
    aboutVenue: 'Velocity Sports Arena is the most popular night sports facility in Koramangala. Perfect for corporate tournaments, weekend leagues, and friendly evening matches with friends.',
    sportsSupported: ['Turf Football', 'Box Cricket'],
    amenities: ['Floodlights', 'Dugout Seating', 'Free Parking', 'First Aid Station', 'Cafeteria & Energy Drinks', 'Clean Restrooms', 'Live Scoreboard'],
    photos: [
      'https://images.unsplash.com/photo-1529900241458-963d11d94f29?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1518604666860-9ed391f76460?w=1000&auto=format&fit=crop&q=80',
    ],
    venueType: 'Outdoor',
    startingPrice: 1200,
    rating: 4.8,
    reviewCount: 52,
    status: FACILITY_STATUS.APPROVED,
    operatingHours: { open: '06:00', close: '24:00' },
  },
  {
    key: 'grandslam',
    name: 'Grand Slam International Tennis Academy',
    location: 'HSR Layout, Sector 3',
    address: '27th Main Road, HSR Layout, Sector 3, Bengaluru, 560102',
    description: 'Four international standard acrylic hard courts and two European red clay courts with certified tennis ball machines and coaching staff.',
    aboutVenue: 'Grand Slam Tennis Academy caters to both competitive tournament contenders and enthusiasts. All courts boast shock-absorbent multi-layer cushioning that minimizes joint fatigue.',
    sportsSupported: ['Tennis', 'Table Tennis'],
    amenities: ['Lockers & Showers', 'Pro Shop & Racquet Restringing', 'Ball Boy Facility', 'Spectator Bleachers', 'Free Parking', 'Floodlights'],
    photos: [
      'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1542144582-1ba00456b5e3?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=1000&auto=format&fit=crop&q=80',
    ],
    venueType: 'Hybrid',
    startingPrice: 700,
    rating: 4.7,
    reviewCount: 29,
    status: FACILITY_STATUS.APPROVED,
    operatingHours: { open: '06:00', close: '22:00' },
  },
  {
    key: 'urbansmash',
    name: 'Urban Smash Hub & Table Tennis Lounge',
    location: 'Whitefield, ITPL Main Road',
    address: 'Behind Brigade Tech Park, Whitefield, Bengaluru, 560066',
    description: 'Six ITTF approved Stag Americas 16 Table Tennis tables and four indoor synthetic badminton courts located in the heart of the tech corridor.',
    aboutVenue: 'Designed for fitness enthusiasts and corporate leagues, Urban Smash Hub provides seamless air-conditioned courts with high ceilings and anti-slip sport flooring.',
    sportsSupported: ['Badminton', 'Table Tennis'],
    amenities: ['Air Conditioning', 'Cafeteria', 'Shower & Changing Rooms', 'Valet Parking', 'Equipment Rental'],
    photos: [
      'https://images.unsplash.com/photo-1534158914592-062992fbe900?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1511067007798-446708063428?w=1000&auto=format&fit=crop&q=80',
    ],
    venueType: 'Indoor',
    startingPrice: 350,
    rating: 4.9,
    reviewCount: 44,
    status: FACILITY_STATUS.APPROVED,
    operatingHours: { open: '06:00', close: '23:00' },
  },
  {
    key: 'novaturf',
    name: 'Nova Multi-Sport Arena (Pending Approval)',
    location: 'Electronic City, Phase 1',
    address: 'Near Infosys Gate 2, Electronic City, Bengaluru, 560100',
    description: 'New multi-sport venue with 2 cricket cages and 2 tennis courts awaiting administrator review.',
    aboutVenue: 'A modern sporting facility designed to serve working professionals in Electronic City.',
    sportsSupported: ['Box Cricket', 'Tennis'],
    amenities: ['Floodlights', 'Parking', 'Restrooms'],
    photos: [
      'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1000&auto=format&fit=crop&q=80',
    ],
    venueType: 'Outdoor',
    startingPrice: 800,
    rating: 4.5,
    reviewCount: 2,
    status: FACILITY_STATUS.PENDING,
    operatingHours: { open: '07:00', close: '22:00' },
  },
];

module.exports = { seedUsers, seedFacilities };
